# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.workers.max=4
org.gradle.configureondemand=false

# Android SDK
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Kotlinx Serialization
kotlinx.serialization.json.allowSpecialFloatingPointValues=true
kotlinx.serialization.json.isLenient=true

# Media3
androidx.media3.exoplayer.enableDecoder=true

# Compose
androidx.compose.material3.confirmState=true